#ifndef _PINOUT_H
#define _PINOUT_H

#include "stm32f4xx_hal.h"
#define RIGHT_MOTOR_PWM_PIN_Pin GPIO_PIN_0
#define RIGHT_MOTOR_PWM_PIN_GPIO_Port GPIOA
#define FLOOR_SENSOR_INT_PIN_Pin GPIO_PIN_1
#define FLOOR_SENSOR_INT_PIN_GPIO_Port GPIOA
#define FLOOR_SENSOR_INT_PIN_EXTI_IRQn EXTI1_IRQn
#define LEFT_SENSOR_INT_PIN_Pin GPIO_PIN_2
#define LEFT_SENSOR_INT_PIN_GPIO_Port GPIOA
#define LEFT_SENSOR_INT_PIN_EXTI_IRQn EXTI2_IRQn
#define RIGHT_SENSOR_INT_PIN_Pin GPIO_PIN_3
#define RIGHT_SENSOR_INT_PIN_GPIO_Port GPIOA
#define RIGHT_SENSOR_INT_PIN_EXTI_IRQn EXTI3_IRQn
#define LEFT_MOTOR_PWM_PIN_Pin GPIO_PIN_5
#define LEFT_MOTOR_PWM_PIN_GPIO_Port GPIOA
#define ENCODER_L_B_Pin GPIO_PIN_7
#define ENCODER_L_B_GPIO_Port GPIOA
#define BUTTON_INT_PIN_Pin GPIO_PIN_5
#define BUTTON_INT_PIN_GPIO_Port GPIOC
#define BUTTON_INT_PIN_EXTI_IRQn EXTI9_5_IRQn
#define RIGHT_MOTOR_REVERSE_Pin GPIO_PIN_14
#define RIGHT_MOTOR_REVERSE_GPIO_Port GPIOB
#define LEFT_MOTOR_REVERSE_Pin GPIO_PIN_15
#define LEFT_MOTOR_REVERSE_GPIO_Port GPIOB
#define FRONT_SENSOR_INT_PIN_Pin GPIO_PIN_13
#define FRONT_SENSOR_INT_PIN_GPIO_Port GPIOA
#define FRONT_SENSOR_INT_PIN_EXTI_IRQn EXTI15_10_IRQn
#define YELLOW_LED_Pin GPIO_PIN_12
#define YELLOW_LED_GPIO_Port GPIOC
#define ENCODER_L_A_Pin GPIO_PIN_4
#define ENCODER_L_A_GPIO_Port GPIOB
#define ENCODER_R_A_Pin GPIO_PIN_6
#define ENCODER_R_A_GPIO_Port GPIOB
#define ENCODER_R_B_Pin GPIO_PIN_7
#define ENCODER_R_B_GPIO_Port GPIOB

#endif
